version: "3.8"

services:
  neo4j:
    image: neo4j:4.4.29
    container_name: my_neo4j_container
    environment:
      NEO4J_AUTH: neo4j/neo4j
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./.neo4j/data:/data
      - ./.neo4j/logs:/logs
      - ./.neo4j/import:/import
      - ./.neo4j/plugins:/plugins
